spring.application.name=sportsalerts

spring.datasource.url=jdbc:postgresql://localhost:5432/sportsalerts
spring.datasource.username=sportsalerts_user
spring.datasource.password=${SPORTSALERTS_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true